<a href="https://colab.research.google.com/github/ashleyholen/Data-Science-Capstone/blob/main/capstone.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#packages
import pandas as pd

In [2]:
#reading in data
energy = pd.read_csv("drive/MyDrive/DS_Capstone/try_this.csv")

In [3]:
#looking at first 5 rows
energy.head()

,description,units,source key,Jan-01,Feb-01,Mar-01,Apr-01,May-01,Jun-01,Jul-01,...,Oct-24,Nov-24,Dec-24,Jan-25,Feb-25,Mar-25,Apr-25,May-25,Jun-25,Jul-25
0,all fuels (utility-scale),thousand megawatthours,ELEC.GEN.ALL-HI-99.M,925,801,873,836,886,874,936,...,836,758,808,762,667,749,751,737,769,811
1,coal,thousand megawatthours,ELEC.GEN.COW-HI-99.M,134,131,137,111,141,137,138,...,--,--,--,--,--,--,--,--,--,--
2,petroleum liquids,thousand megawatthours,ELEC.GEN.PEL-HI-99.M,726,613,691,653,669,660,725,...,651,584,644,591,513,540,541,505,553,578
3,petroleum coke,thousand megawatthours,ELEC.GEN.PC-HI-99.M,--,--,--,--,--,--,--,...,--,--,--,--,--,--,--,--,--,--
4,natural gas,thousand megawatthours,ELEC.GEN.NG-HI-99.M,0,0,0,0,0,0,0,...,--,--,--,--,--,--,--,--,--,--

In [4]:
# take out units and source key col first

cols_to_drop = ['units', 'source key']
energy = energy.drop(columns=cols_to_drop)

In [5]:
# melt from wide to long format
df_long = energy.melt(
    id_vars=["description"], # keep fuel type
    var_name="date_str", # new column for the old column names
    value_name="net_generation" # new column for values
)

In [6]:
df_long.head()

                 description date_str net_generation
0  all fuels (utility-scale)   Jan-01            925
1                       coal   Jan-01            134
2          petroleum liquids   Jan-01            726
3             petroleum coke   Jan-01             --
4                natural gas   Jan-01              0

In [7]:
df_long.tail()

                         description date_str net_generation
5600   hydro-electric pumped storage   Jul-25             --
5601                           other   Jul-25             25
5602                       all solar   Jul-25            264
5603  small-scale solar photovoltaic   Jul-25            160
5604         all utility-scale solar   Jul-25            104

In [8]:
df_long

                         description date_str net_generation
0          all fuels (utility-scale)   Jan-01            925
1                               coal   Jan-01            134
2                  petroleum liquids   Jan-01            726
3                     petroleum coke   Jan-01             --
4                        natural gas   Jan-01              0
...                              ...      ...            ...
5600   hydro-electric pumped storage   Jul-25             --
5601                           other   Jul-25             25
5602                       all solar   Jul-25            264
5603  small-scale solar photovoltaic   Jul-25            160
5604         all utility-scale solar   Jul-25            104

[5605 rows x 3 columns]

In [14]:
# replace '--' and 'NM' with NaN, convert to float
# i don't know what 'NM' stands for... "not metered"?
df_long["net_generation"] = (
    df_long["net_generation"]
    .replace({"--": pd.NA, "NM": pd.NA})
)

df_long["net_generation"] = pd.to_numeric(df_long["net_generation"], errors="coerce")

# convert date_str like "Jan-01" into a real datetime
df_long["date"] = pd.to_datetime(df_long["date_str"], format="%b-%y")
df_long["date"] = df_long["date"].dt.strftime("%b %Y")

# rename description as fuel_type and select final columns to keep
tidy_df = df_long.rename(columns={"description": "fuel_type"})[
    ["date", "fuel_type", "net_generation"]
]

In [15]:
tidy_df.head()

       date                  fuel_type  net_generation
0  Jan 2001  all fuels (utility-scale)           925.0
1  Jan 2001                       coal           134.0
2  Jan 2001          petroleum liquids           726.0
3  Jan 2001             petroleum coke             NaN
4  Jan 2001                natural gas             0.0

In [16]:
tidy_df

          date                       fuel_type  net_generation
0     Jan 2001       all fuels (utility-scale)           925.0
1     Jan 2001                            coal           134.0
2     Jan 2001               petroleum liquids           726.0
3     Jan 2001                  petroleum coke             NaN
4     Jan 2001                     natural gas             0.0
...        ...                             ...             ...
5600  Jul 2025   hydro-electric pumped storage             NaN
5601  Jul 2025                           other            25.0
5602  Jul 2025                       all solar           264.0
5603  Jul 2025  small-scale solar photovoltaic           160.0
5604  Jul 2025         all utility-scale solar           104.0

[5605 rows x 3 columns]